stages:

  first_handle_data:
    cmd: python3 -m src.data.read_data data/raw/data_yandex.csv data/interim/data_first_handle.csv
    deps:
      - data/raw/data_yandex.csv
      - src/data/read_data.py
    outs:
      - data/interim/data_first_handle.csv

  calc_hdb:
    cmd: python3 -m src.data.calculate_hdb data/interim/data_first_handle.csv data/interim/data_with_hdb.csv
    deps:
      - data/interim/data_first_handle.csv
      - src/data/calculate_hdb.py
    outs:
      - data/interim/data_with_hdb.csv

  calc_freq_components:
    cmd: python3 -m src.features.get_freq_components data/interim/data_with_hdb.csv data/processed/data_search.csv
    deps:
      - data/interim/data_with_hdb.csv
      - src/features/get_freq_components.py
    params:
      - data_feature.day_freq
    outs:
      - data/processed/data_search.csv

  train_model:
    cmd: python3 -m src.models.train_model data/processed/data_search.csv models/saved_model
    deps:
      - data/processed/data_search.csv
      - src/models/train_model.py
      - src/features/window_generator.py
      - src/config.py
      - src/models/attention_decoder.py
      - src/models/attention_encoder.py
      - src/models/da_rnn_model.py
    params:
      - train.window_size
      - train.max_epochs
      - train.num_hidden_state
      - train.patience
      - train.batch_size
      - train.seed
      - train.steps_per_epoch
      - train.validation_steps
    outs:
      - models/saved_model/weights/checkpoint
      - models/saved_model/weights/checkpoint.data-00000-of-00001
      - models/saved_model/weights/checkpoint.index

  evaluate_validation:
    cmd: python3 -m src.models.evaluate_validation data/processed/data_search.csv models/saved_model/
    deps:
      - data/processed/data_search.csv
      - models/saved_model/weights/checkpoint
      - models/saved_model/weights/checkpoint.data-00000-of-00001
      - models/saved_model/weights/checkpoint.index
      - src/models/evaluate_validation.py
      - src/config.py
      - src/func.py
      - src/features/window_generator.py
      - src/visualization/calculate_metrics.py
      - src/visualization/plot_window.py
    params:
      - train.window_size
      - train.num_hidden_state
      - train.batch_size
      - train.seed
      - train.n_future
    outs:
      - reports/validation_metric/metric_all_window.csv
    metrics:
      - reports/validation_metric/average_metric.json

  evaluate_test:
    cmd: python3 -m src.models.evaluate_test data/processed/data_search.csv models/saved_model/
    deps:
      - data/processed/data_search.csv
      - models/saved_model/weights/checkpoint
      - models/saved_model/weights/checkpoint.data-00000-of-00001
      - models/saved_model/weights/checkpoint.index
      - src/models/evaluate_test.py
      - src/config.py
      - src/func.py
      - src/features/window_generator.py
      - src/visualization/calculate_metrics.py
      - src/visualization/plot_window.py
    params:
      - train.window_size
      - train.num_hidden_state
      - train.batch_size
      - train.seed
      - train.n_future
    outs:
      - reports/test_metric/metric_all_window.csv
    metrics:
      - reports/test_metric/average_metric.json

plots:
  - validation_metric_mape:
      y:
        reports/validation_metric/metric_all_window.csv: [MAPE]
  - validation_metric_rmse:
      y:
        reports/validation_metric/metric_all_window.csv: [RMSE]
  - test_metric_mape:
      y:
        reports/test_metric/metric_all_window.csv: [MAPE]
  - test_metric_rmse:
      y:
        reports/test_metric/metric_all_window.csv: [RMSE]
